### ISSUE TITLE
documentation progress tracker

### ISSUE THREAD

**Issue by Eisverygoodletter** [rm-robotics/ev3dev-cpp-template-wrapper#27]
# This issue is for submitting / discussing / tracking problems in the [readme-tutorials](/rshs-robotics-club/ev3dev-cpp-template-wrapper/tree/readme-tutorials) branch, and the [docs](rshs-robotics-club/ev3dev-cpp-template-wrapper)

## follow this format

current issues:
- [x] `MotorPair.runMotorsForever` is sometimes referred to as `MotorPair.runForever`

**Comment by Eisverygoodletter** [comment]
current issues:
- [x] lack of documentation for everything
- [x] documentation needs to be updated for irseeker sensor

**Comment by txvvgnx** [comment]
- [x] max speed method is private and therefore is inaccessible, make it public with maths

**Comment by Eisverygoodletter** [comment]
- [x] A plan needs to be created for smooth transition from the version 1 build structure to the version 2 build structure

**Comment by Eisverygoodletter** [comment]
# Version 2.5.0 feature updates checklist
- [x] `Omni` class needs to be rewritten (currently too much spaghetti)
- [x] A `Vector` class needs to be implemented.

# Version 2.5.0 documentation preparations checklist
- [x] Installation steps
- [x] Common bugs and solutions file, including:
    - [x] LF vs CRLF line endings
    - [x] docker daemon is not responding
    - [x] No such image `ev3dev-latest` or similar
    - [x] can't run the .sh file
- [x] Contribution guidelines
    - [x] branch naming patterns
    - [x] asking for requirements in issues
    - [x] Basic Guide on how the CMake build system works (detailed guide coming later)
- [x] Library updates
    - [x] new port naming system
    - [x] `i2c` vs the average lego port (drivers and their naming)
    - [x] `Omni` class rebuilt docs
    - [x] `Vector` class new docs
- [x] Aesthetics updates
    - [x] make the forked just-the-docs theme have darker characters 
---
#### stuff will be added to this list as required later

**Comment by Eisverygoodletter** [comment]
We will be opening up a new issue for future updates
