### ISSUE TITLE
Tracker issue for V3.0.0

### ISSUE THREAD

**Issue by Eisverygoodletter** [rm-robotics/ev3dev-cpp-template-wrapper#56]
# Goal of version `3.0.0`
#### In the previous versions, although the core purpose of the library was for RCJA soccer competitions using ev3 robots, the effort to keep this library general purpose has forced us to leave many unnecessary "features", slowing down compile time and space. In version `3.0.0`, the goal is to specialize the library for RCJA soccer competitions. A fork may be created in the future from `2.5.2` to create a general purpose version, but this repository's version will be specialized for RCJA soccer competitions. This will also allow us to give the library a better name than `ev3dev-cpp-template-wrapper`

# Version `3.0.0` will contain

## Core library content
- [x] reduce unnecessary inheritance of classes and unneeded content
    - [x] `IrSeeker` -> `HiTechnicIrSeeker`
    - [x] `CompassSensor` -> `HiTechnicCompass`
    - [x] `Gyro` -> removed
    - [x] `MotorPair` -> removed
    - [x] `touch` -> removed
    - [x] `lcd` -> removed
    - [x] `Motor` -> remove run for timed functions
- [x] Enhancement of currently available features
    - [x] Potential optimization for `HiTechnicCompass`'s constructor (initialization of the `degreeOffsets` array without the usage of `std::memcpy` (**HELP WANTED**)
    - [x] `static` publicly available functions from `Blockable`
- [x] New features
    - [x] support for `BBSIrSeeker` from buildingblockrobotics.com

- [x] Compilation and linking
    - [x] new custom docker image (`eisverygoodletter/debian-stretch-cross`)
        - [x] `CMake` version `3.24.0`
    - [x] new options when running `./scripts/compile.sh`
        - [x] `-w` for wipe bin folder and rebuild completely
        - [x] `-n` for reconfigure cmake files
        - [x] `-Os` or other optimization flags to pass to the compiler (default `-Os`)
    - [x] find a solution for fixing clock skew with `Make` (**HELP WANTED**)
- [x] Documentation
    - [x] Rename class names

More details may be added later.
Note that new documentation will not be added until a better documentation system is used

**Comment by Eisverygoodletter** [comment]
It seems like clock skew can be fixed by restarting your computer :P
